### ISSUE TITLE
respond if possible 

### ISSUE THREAD

**Issue by G4judge** [CodeRuner5235/SteamDeck-Auto-TDP#2]
ive seen your video of hackintosh on your steam deck and been interested https://www.youtube.com/watch?v=yaPVjdHW2dA 

your EFI file has been taken down and me and some people are making custom drivers for the steam deck pls reply if possible

**Comment by CodeRunner5235** [comment]
Oh, whoops, my mistake. Fixed the link to the video and the GitHub repository. Here is the new link: https://github.com/CodeRunner5235/Opencore-Steam-Deck

Thanks!

**Comment by G4judge** [comment]
thank you my friend 

me and some people in the hackintosh amd discord server are making custom drivers for steam deck hackintosh audio wifi touch video acceleration etc but thanks once again

**Comment by CodeRunner5235** [comment]
I look forward to seeing what you guys accomplish! Good luck!

**Comment by G4judge** [comment]
do you have discord?

**Comment by CodeRunner5235** [comment]
Yes I do. Yall said you are in the AMD hackintosh server?

**Comment by G4judge** [comment]
yes my username  is @mysterious_creature1 on discord
