### ISSUE TITLE
Steam Deck OLED

### ISSUE THREAD

**Issue by Wayne992** [CodeRuner5235/SteamDeck-Auto-TDP#3]
Hey, 
Ist there any way to get this to Work on the OLED?

**Comment by CodeRunner5235** [comment]
Hey! 
The latest steamOS and decky updates should render this obsolete. That being said: https://github.com/CodeRunner5235/SteamDeck-Auto-TDP/pull/1

this kind soul did the work for it to work on OLED. Just edit the paths and your off to the races.
